{ ... }:

{

  imports = [
    # overriding package sets and such
    ./nixpkgs-configuration.nix

    # the results of the hardware scan generated by nixos-install
    ./hardware-configuration.nix

    # bootloader, zfs, etc.
    ./boot-and-filesystems.nix

    # networking setup
    ./networking.nix

    # video, graphics
    ./graphics.nix

    # audio, sound
    ./sound.nix

    # services
    ./services.nix

    # home-manager NixOS module
    <home-manager/nixos>

    # home-manager setup for the primary user
    ./users/me
  ];

  documentation.dev.enable = true;
  documentation.doc.enable = true;

  hardware.cpu.intel.updateMicrocode = true;

  environment.systemPackages = [ ];
  environment.pathsToLink = [ "/share/zsh" ];

  # Select internationalisation properties.
  console = {
    font = "Lat2-Terminus16";
    keyMap = "us";
  };

  # TODO set currency etc
  # TODO should we do this at the home-manager level?
  # probably not but still
  i18n.defaultLocale = "en_US.UTF-8";

  # Set your time zone.
  time.timeZone = "Asia/Kolkata";

  # This value determines the NixOS release with which your system is to be
  # compatible, in order to avoid breaking some software such as database
  # servers. You should change this only after NixOS release notes say you
  # should.
  system.stateVersion = "19.09"; # Did you read the comment?

}

