{ config, lib, pkgs, ... }:

let

  hm-nixos = (import ./pinned.nix).home-manager.nixos;

in rec {

  imports = [
    # overriding package sets and such
    ./nixpkgs-configuration.nix

    # the results of the hardware scan generated by nixos-install
    ./hardware-configuration.nix

    # bootloader, zfs, etc.
    ./boot-and-filesystems.nix

    # i18n, timezones, etc
    # TODO find better name
    ./system-configuration.nix

    # networking setup
    ./networking.nix

    # video, graphics
    ./graphics.nix

    # audio, sound
    ./sound.nix
    
    # services
    ./services.nix

    # home-manager NixOS module
    hm-nixos

    ./users/me
  ];

  # options zfs_vdev_cache_bshift=18
  # options l2arc_feed_again=0
  # options zfs zfs_compressed_arc_enable=1

  environment.systemPackages = [ ];
  environment.pathsToLink = [ "/share/zsh" ];


  # This value determines the NixOS release with which your system is to be
  # compatible, in order to avoid breaking some software such as database
  # servers. You should change this only after NixOS release notes say you
  # should.
  system.stateVersion = "19.09"; # Did you read the comment?

}

