--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/rlptgod/.config/wpg/wallpapers/pawel-czerwinski-sE97eb0WhGI-unsplash(1).jpg"

-- Special
background="#131020"
foreground="#c1c1ce"
cursor="#c1c1ce"

-- Colors
color0="#131020"
color1="#B93E4A"
color2="#5468c2"
color3="#8454aa"
color4="#676B96"
color5="#916C99"
color6="#82859D"
color7="#c1c1ce"
color8="#878790"
color9="#B93E4A"
color10="#5468c2"
color11="#8454aa"
color12="#676B96"
color13="#916C99"
color14="#82859D"
color15="#c1c1ce"
