--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/rlptgod/img/walls/lucas-benjamin-R79qkPYvrcM-unsplash.jpg"

-- Special
background="#00041E"
foreground="#92c7d5"
cursor="#92c7d5"

-- Colors
color0="#00041E"
color1="#614F69"
color2="#9B0637"
color3="#B3345A"
color4="#DF1E56"
color5="#096993"
color6="#56698D"
color7="#92c7d5"
color8="#668b95"
color9="#614F69"
color10="#9B0637"
color11="#B3345A"
color12="#DF1E56"
color13="#096993"
color14="#56698D"
color15="#92c7d5"
